<a href="https://colab.research.google.com/github/hibana2077/Fail-Side-Projects/blob/main/ETH_adderss_decoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install web3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
!pip install --upgrade tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
!touch myfile.csv

In [5]:
!nvidia-smi

Mon Jun  6 13:03:42 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P0    28W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [6]:
#匯入
from bs4 import BeautifulSoup
from web3 import Web3
from timeit import default_timer as timer
from eth_account import Account
import requests,json,secrets,hashlib
import pandas as pd
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
#連接到ETH驗證者節點
w3=Web3(Web3.HTTPProvider('https://eth-mainnet.alchemyapi.io/v2/r5LWV9YohEw08-xtCrMjWcWy0q64_KJq'))
zscore=(int('0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364140',16)-1)
zscore_ad=int('0xffffffffffffffffffffffffffffffffffffffff',16)
#data={'num':['ad','pk','ad_sha2_256','ad_sha1','ad_sha3_256']}
#data={'num':['ad','ad_sha2_256','pk']}
data={'num':['ad0','ad1','ad2','ad3','ad4','ad5','ad6','ad7','ad8','ad9','ad10','ad11','ad12','ad13','ad14','ad15','ad16','ad17','ad18','ad19','ad20','ad21','ad22','ad23','ad24','ad25','ad26','ad27','ad28','ad29','ad30','ad31','ad32','ad33','ad34','ad35','ad36','ad37','ad38','ad39','pk0','pk1','pk2','pk3','pk4','pk5','pk6','pk7','pk8','pk9','pk10','pk11','pk12','pk13','pk14','pk15','pk16','pk17','pk18','pk19','pk20','pk21','pk22','pk23','pk24','pk25','pk26','pk27','pk28','pk29','pk30','pk31','pk32','pk33','pk34','pk35','pk36','pk37','pk38','pk39','pk40','pk41','pk42','pk43','pk44','pk45','pk46','pk47','pk48','pk49','pk50','pk51','pk52','pk53','pk54','pk55','pk56','pk57','pk58','pk59','pk60','pk61','pk62','pk63']}
def createAddress():#CPU
  priv = secrets.token_hex(32)
  private_key = "0x" + priv
  acct = Account.from_key(private_key)
  return private_key, acct.address

def task1(st):
  s=timer()
  pk,ad=createAddress()
  ad=str(ad).lower()
  #data[st]=[int(ad,16)/10**31,int(pk,16)/10**62,int(hashlib.sha256(ad.encode()).hexdigest(),16)/10**74,int(hashlib.sha1(ad.encode()).hexdigest(),16)/10**46,int(hashlib.sha3_256(ad.encode()).hexdigest(),16)/10**74]
  #data[st]=[ad,pk,hashlib.sha256(ad.encode()).hexdigest(),hashlib.sha1(ad.encode()).hexdigest(),hashlib.sha3_256(ad.encode()).hexdigest()]
  #data[st]=[list(map(lambda x:int(x,16),list(ad[2:]))),list(map(lambda x:int(x,16),list(hashlib.sha256(ad.encode()).hexdigest()))),list(map(lambda x:int(x,16),list(pk[2:])))]
  data[st]=list(map(lambda x:int(x,16),list(ad[2:])))+list(map(lambda x:int(x,16),list(pk[2:])))
  #data[st]=[int(ad,16)/zscore_ad,int(hashlib.sha256(ad.encode()).hexdigest(),16)/zscore,(int(pk,16)-1)/zscore]
  print(f"time using:{timer()-s:.4f}s porcess:{(st/end)*100:.4f} % st:{st}")
st=0
end=250000
while st<end:
  st+=1
  task1(st)
#np.savetxt('myfile.csv',data, delimiter=',')
df = pd.DataFrame(data)
df = df.T
df.to_csv('myfile.csv',index=True)

串流輸出內容已截斷至最後 5000 行。
time using:0.0044s porcess:98.0004 % st:245001
time using:0.0044s porcess:98.0008 % st:245002
time using:0.0041s porcess:98.0012 % st:245003
time using:0.0045s porcess:98.0016 % st:245004
time using:0.0043s porcess:98.0020 % st:245005
time using:0.0044s porcess:98.0024 % st:245006
time using:0.0044s porcess:98.0028 % st:245007
time using:0.0046s porcess:98.0032 % st:245008
time using:0.0044s porcess:98.0036 % st:245009
time using:0.0044s porcess:98.0040 % st:245010
time using:0.0042s porcess:98.0044 % st:245011
time using:0.0045s porcess:98.0048 % st:245012
time using:0.0045s porcess:98.0052 % st:245013
time using:0.0045s porcess:98.0056 % st:245014
time using:0.0043s porcess:98.0060 % st:245015
time using:0.0044s porcess:98.0064 % st:245016
time using:0.0045s porcess:98.0068 % st:245017
time using:0.0046s porcess:98.0072 % st:245018
time using:0.0043s porcess:98.0076 % st:245019
time using:0.0044s porcess:98.0080 % st:245020
time using:0.0046s porcess:98.0084 % st

In [7]:
df.columns=['ad0','ad1','ad2','ad3','ad4','ad5','ad6','ad7','ad8','ad9','ad10','ad11','ad12','ad13','ad14','ad15','ad16','ad17','ad18','ad19','ad20','ad21','ad22','ad23','ad24','ad25','ad26','ad27','ad28','ad29','ad30','ad31','ad32','ad33','ad34','ad35','ad36','ad37','ad38','ad39','pk0','pk1','pk2','pk3','pk4','pk5','pk6','pk7','pk8','pk9','pk10','pk11','pk12','pk13','pk14','pk15','pk16','pk17','pk18','pk19','pk20','pk21','pk22','pk23','pk24','pk25','pk26','pk27','pk28','pk29','pk30','pk31','pk32','pk33','pk34','pk35','pk36','pk37','pk38','pk39','pk40','pk41','pk42','pk43','pk44','pk45','pk46','pk47','pk48','pk49','pk50','pk51','pk52','pk53','pk54','pk55','pk56','pk57','pk58','pk59','pk60','pk61','pk62','pk63']
df=df.drop('num',axis=0)
df.to_csv('myfile.csv',index=True)

In [8]:
df

ad0 ad1 ad2 ad3 ad4 ad5 ad6 ad7 ad8 ad9  ... pk54 pk55 pk56 pk57 pk58  \
1       12  15  10   1   5  14   9   7  11   4  ...    5    9   10    5   15   
2       14  13   2   1   6  12   3  15  15   5  ...   10   14    2   10   10   
3        0   0   5   5   6   9   4  10  14   3  ...   13   14    2    3    1   
4        4   9  11   3   0  10   0  10   0   7  ...   10    2    9    1   13   
5       14  11  15  14  10   4  11  15   3   1  ...   15   11   11   11   14   
...     ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
249996  13   0   9   4  13  14   2  11   9   1  ...   11    2   12    8    1   
249997   5  14   8   7  11   2  10   9  11   2  ...    6   14   11   11    6   
249998   1   0  12   6  15  11   6   3  13   5  ...    5    3   11    8    4   
249999   8   0  15   0  12   7   0   5  10   4  ...   14    5    7    7   14   
250000   7   5   9  13  12   5  14   4  14   7  ...   12    6    8    1   13   

       pk59 pk60 pk61 pk62 pk63  
1        15   12    4   14   14  
2         4    6    3   10    2  
3         5    6    6    0   12  
4        13    3    3   13    6  
5        13    1   12    2   11  
...     ...  ...  ...  ...  ...  
249996    1   10   13    0   12  
249997    6   14    3    2    4  
249998    9    9    3    7    6  
249999   11    2    7   15   14  
250000   10    6    3   14    0  

[250000 rows x 104 columns]

In [9]:
#split data
from keras import backend as K
dataset = df.values
np.random.shuffle(dataset)

In [10]:
X=dataset[:,0:40]
Y=dataset[:,40:]


X_train1 = K.cast_to_floatx(X)
Y_train1 = K.cast_to_floatx(Y)

'''X=X.reshape(50000,input_dim).astype("int32")'''

'X=X.reshape(50000,input_dim).astype("int32")'

In [16]:
print(len(X_train1[0]))

40


In [12]:
print(Y_train1)

[[12.  8. 10. ...  0.  4. 13.]
 [11. 15.  9. ...  7. 10. 10.]
 [13. 13.  0. ...  8.  9.  0.]
 ...
 [ 9. 15.  2. ...  9. 11.  6.]
 [ 0.  3.  3. ...  4. 15. 11.]
 [ 4. 13.  4. ... 11.  8. 12.]]


In [29]:
model=Sequential()
model.add(Dense(64,input_shape=(40,),activation="sigmoid"))
model.add(Dense(128,activation="sigmoid"))
model.add(Dense(256,activation="tanh"))
model.add(Dense(128,activation="sigmoid"))
model.add(Dense(64,activation="linear"))
model.summary()
#更換activation func

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 64)                2624      
                                                                 
 dense_19 (Dense)            (None, 128)               8320      
                                                                 
 dense_20 (Dense)            (None, 256)               33024     
                                                                 
 dense_21 (Dense)            (None, 128)               32896     
                                                                 
 dense_22 (Dense)            (None, 64)                8256      
                                                                 
Total params: 85,120
Trainable params: 85,120
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(momentum=0.9), metrics=['mse','mae','RootMeanSquaredError'])
#更換loss func and optimizer

In [31]:
model.fit(X_train1,Y_train1,epochs=15,batch_size=128)

Epoch 1/15
1954/1954 [==============================] - 8s 4ms/step - loss: 21.5158 - mse: 21.5158 - mae: 4.0154 - root_mean_squared_error: 4.6385
Epoch 2/15
1954/1954 [==============================] - 7s 4ms/step - loss: 21.2727 - mse: 21.2727 - mae: 4.0004 - root_mean_squared_error: 4.6122
Epoch 3/15
1954/1954 [==============================] - 7s 4ms/step - loss: 21.2711 - mse: 21.2711 - mae: 4.0003 - root_mean_squared_error: 4.6121
Epoch 4/15
1954/1954 [==============================] - 7s 4ms/step - loss: 21.2700 - mse: 21.2700 - mae: 4.0004 - root_mean_squared_error: 4.6119
Epoch 5/15
1954/1954 [==============================] - 7s 4ms/step - loss: 21.2690 - mse: 21.2690 - mae: 4.0004 - root_mean_squared_error: 4.6118
Epoch 6/15
1954/1954 [==============================] - 8s 4ms/step - loss: 21.2680 - mse: 21.2680 - mae: 4.0004 - root_mean_squared_error: 4.6117
Epoch 7/15
1954/1954 [==============================] - 7s 4ms/step - loss: 21.2676 - mse: 21.2676 - mae: 4.0005 - roo

In [32]:
#loss,accuracy = model.evaluate(X_train1,Y_train1)
print(model.evaluate(X_train1,Y_train1))
#print(f"準確度:{accuracy:.2f}")

7813/7813 [==============================] - 23s 3ms/step - loss: 21.2657 - mse: 21.2657 - mae: 4.0003 - root_mean_squared_error: 4.6115
[21.265708923339844, 21.265708923339844, 4.000328540802002, 4.611475467681885]


In [33]:
X=dataset[0:10,0:40]
Y=dataset[0:10,40:]


X_val = K.cast_to_floatx(X)
Y_val = K.cast_to_floatx(Y)

In [34]:
Y_pred=model.predict(X_val,batch_size=10,verbose=0)
for now in range(10):
  Y_MIN,Y_MAX=min((Y_pred[now])),max((Y_pred[now]))
  print('0x'+''.join(''.join(list(map(lambda x:hex(int(x)),X_val[now]))).split('0x')))
  print('0x'+''.join(''.join(list(map(lambda x:hex(int(x)),Y_val[now]))).split('0x')))
  print('0x'+''.join(''.join(list(map(lambda x:hex(int(x)),(Y_pred[now]-Y_MIN)/(Y_MAX-Y_MIN)*15))).split('0x')))
  print((Y_pred[now]-Y_MIN)/(Y_MAX-Y_MIN)*15)

0x4b1b4f7d291f1ec3bcb4d13e31b12383e518fcce
0xc8a608077a6d21edd690ff4b839147553a403823b8fad975bb6d1f857110704d
0xf19692633748358b658e74787d393903950694605842961543671541669373cc
[15.          1.8730382   9.475913    6.0241876   9.973446    2.9753249
  6.592962    3.7629619   3.8326688   7.3751616   4.0113764   8.040441
  3.7852697   5.954466    8.191389   11.417783    6.362982    5.909764
  8.932589   14.389923    7.846513    4.983359    7.5667377   8.184159
  7.5010614  13.207213    3.8948586   9.977477    3.9217713   9.827361
  0.          3.4815512   9.191318    5.4117866   0.41184402  6.8749895
  9.956259    4.38955     6.2789145   0.5446159   5.352796    8.595716
  4.9567327   2.8565402   9.811394    6.155539    1.0815712   5.5484176
  4.78022     3.8975983   6.494247    7.757854    1.730798    5.154937
  4.635899    1.4623992   6.8867097   6.047686    9.079935    3.136301
  7.270995    3.118713   12.164305   12.144779  ]
0x2955f3e52e9427ace934e7725cab3ac5bf670430
0xbf9314688abdb17

工作紀錄:</br>
把數字正規畫的方法改成用陣列的方式去做訓練</br>
loss func 和 active func可以不用更動